In [50]:
import numpy as np
x = np.array([[1,1,1],[1,2,3]])
x.shape


(2, 3)

In [55]:
y = np.array([1,0])
y.dot(x)



array([1, 1, 1])

array([[1, 1, 1],
       [1, 4, 6]])

In [45]:

z

array([3, 2, 3])